dosisgateway:
  storagefolder: target
  wip:
    highwater: 5000
    lowwater: 4000
  poller:
    delay: 150
    instances:
      -   name: dev
          url: http://localhost:29090/
          itemlimit: 100
          backoffBase: 10
          backoffExponent: 3
          backoffMaxRetries: 10
      -   name: fout
          url: http://localhost:29090/fout
          itemlimit: 100
          backoffBase: 10
          backoffExponent: 3
          backoffMaxRetries: 3
