dosisgateway:
  storagefolder: target
  wip:
    highwater: 5000
    lowwater: 4000
  poller:
    delay: 150
    instances:
      -   name: dev
          url: http://localhost:29090/
          itemlimit: 100
          backoffBase: 10
          backoffExponent: 3
          backoffMaxRetries: 10
#      -   name: fout
#          url: http://localhost:29090/fout
#          itemlimit: 100
#          backoffBase: 10
#          backoffExponent: 3
#          backoffMaxRetries: 3
  dosis:
    clientId: 6776
    tokenUrl: https://beta.oauth.vlaanderen.be/authorization/ws/oauth/v2/token
    baseUrl: https://beta.dosis.dev-vlaanderen.be
    bronUri: urn://ovam/evoa
    privateWebKey: jsonwebkeyprivate.key
    delay: 150
    backoffBase: 10
    backoffExponent: 3
    backoffMaxRetries: 10
    showSecurityInManagementApi: false

logging:
  level:
    org:
      apache:
        http: ERROR
    httpclient:
      wire: ERROR
    be:
      vlaio:
        dosis: INFO
spring:
  task:
    scheduling:
      pool:
        size: 5 # Set this to at least  2 + nb of pollers.
