dosisgateway:
  storagefolder: target
  wip:
    highwater: 5000
    lowwater: 4000
  poller:
    delay: 150
    instances:
      -   name: dev
          url: http://some.url/
          itemlimit: 100
      -   name: test
          url: http://some.test.url/
          itemlimit: 100
